version: '2'
services:
  mysql:
        image: mysql:5.6
#        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=db_user
        ports:
          - "3306:3306"
  website:
    container_name: php72
    build:
      context: ./
    volumes:
      - D:/ACML/ACMLProject/src:/var/www/html
    ports:
      - 8081:80
    depends_on:
      - mysql