version: '2'
services:
  mysql:
        image: mysql:5.6
#        working_dir: /application
        volumes:
          - ./dump:/docker-entrypoint-initdb.d
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=testuser
          - MYSQL_PASSWORD=testpassword
        ports:
          - "3306:3306"
  website:
    container_name: php72
    build:
      context: ./
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql